---
- name: APACHE_EXPORTER | Ensure apache_exporter group
  group:
    name: "{{ apache_exporter_group }}"

- name: APACHE_EXPORTER | Ensure apache_exporter user
  user:
    name: "{{ apache_exporter_user }}"
    group: "{{ apache_exporter_group }}"

- name: APACHE_EXPORTER | Ensure skeleton paths
  file:
    path: "{{ item }}"
    owner: "{{ apache_exporter_user }}"
    group: "{{ apache_exporter_group }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ apache_exporter_install_path }}"
    - "{{ apache_exporter_log_path }}"

- name: APACHE_EXPORTER | Download and extract package
  unarchive:
    copy: no
    src: "{{ apache_exporter_url }}"
    dest: "{{ apache_exporter_install_path }}"
    extra_opts: "--strip-components=1"
    mode: 0755
    owner: "{{ apache_exporter_user }}"
    group: "{{ apache_exporter_group }}"
  when: apache_exporter_is_installed == false or apache_exporter_is_different_version == true

- name: APACHE_EXPORTER | Link binary
  file:
    src: "{{ apache_exporter_install_path }}/apache_exporter"
    dest: "/usr/bin/apache_exporter"
    state: link
  when: apache_exporter_is_installed == false or apache_exporter_is_different_version == true

- name: APACHE_EXPORTER | Copy Daemon script
  template:
    src: apache_exporter.service.j2
    dest: /etc/systemd/system/apache_exporter.service
    mode: 0644
  notify: restart apache_exporter
